/* @generated by scripts/generate-native-protocol.ts; do not edit. */
#ifndef REFRAIN_NATIVE_H
#define REFRAIN_NATIVE_H
#include <stdint.h>
#define REFRAIN_PROTOCOL_VERSION 2
#define REFRAIN_API_VERSION 1
#define REFRAIN_CAPABILITY_MASK 1
#define REFRAIN_PROJECTION_BYTES 40960
#define REFRAIN_EVENT_TEXT_BYTES 12000
#define REFRAIN_DEFAULT_VIEWPORT_BLOCKS 96
#define REFRAIN_VIRTUAL_BLOCK_HEIGHT 36
#define REFRAIN_PROTOCOL_FINGERPRINT "f21e1dcfa20d362a6744371f720fa945b36cf508c772d639d5b7c6a53d672aa1"
#define REFRAIN_ERROR_PROTOCOL_MISMATCH 1
#define REFRAIN_ERROR_INVALID_REQUEST 2
#define REFRAIN_ERROR_UNKNOWN_SESSION 3
#define REFRAIN_ERROR_DOMAIN_REFUSAL 4
#define REFRAIN_ERROR_HOST_FAILURE 5
#define REFRAIN_ERROR_STALE_REVISION 6
typedef struct RefrainNativeRequest {
  uint16_t protocol_version;
  uint16_t action;
  uint16_t input;
  uint16_t flags;
  uint64_t session;
  uint64_t revision;
  uint64_t window_start;
  uint64_t anchor;
  uint64_t focus;
  uint64_t cursor;
  uint64_t viewport_first_block;
  uint32_t viewport_block_count;
  uint32_t text_len;
  uint8_t text[REFRAIN_EVENT_TEXT_BYTES];
} RefrainNativeRequest;
typedef struct RefrainNativeResponse {
  uint32_t status;
  uint16_t protocol_version;
  uint16_t api_version;
  uint32_t capabilities;
  uint16_t action;
  uint16_t reserved;
  uint64_t session;
  uint64_t revision;
  uint64_t total_bytes;
  uint64_t total_blocks;
  uint64_t window_start;
  uint64_t first_block;
  uint32_t block_count;
  uint32_t text_len;
  uint32_t composition_len;
  uint32_t projection_reserved;
  uint64_t selection_anchor;
  uint64_t selection_focus;
  uint64_t composition_start;
  uint64_t composition_end;
  uint64_t composition_cursor;
  uint8_t text[REFRAIN_PROJECTION_BYTES];
  uint8_t composition[REFRAIN_EVENT_TEXT_BYTES];
} RefrainNativeResponse;
RefrainNativeResponse refrain_native_dispatch(RefrainNativeRequest request);
#endif
