/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * Copyright (c) 2026 2youg1 and the RefRain contributors */
/* @generated by scripts/generate-native-protocol.ts; do not edit. */
#ifndef REFRAIN_NATIVE_H
#define REFRAIN_NATIVE_H
#include <stdint.h>
#define REFRAIN_PROTOCOL_VERSION 6
#define REFRAIN_API_VERSION 1
#define REFRAIN_CAPABILITY_MASK 1
#define REFRAIN_PROJECTION_BYTES 40960
#define REFRAIN_EVENT_TEXT_BYTES 12000
#define REFRAIN_DEFAULT_VIEWPORT_BLOCKS 96
#define REFRAIN_VIRTUAL_BLOCK_HEIGHT 36
#define REFRAIN_ANCHOR_RANGE_CAPACITY 512
#define REFRAIN_PROTOCOL_FINGERPRINT "2be82cd976501fb657b6db59d738537fcaf6dba256c3e85ee74bc34d8a66c033"
#define REFRAIN_ERROR_PROTOCOL_MISMATCH 1
#define REFRAIN_ERROR_INVALID_REQUEST 2
#define REFRAIN_ERROR_UNKNOWN_SESSION 3
#define REFRAIN_ERROR_DOMAIN_REFUSAL 4
#define REFRAIN_ERROR_HOST_FAILURE 5
#define REFRAIN_ERROR_STALE_REVISION 6
typedef struct RefrainNativeRequest {
  uint16_t protocol_version;
  uint16_t action;
  uint16_t input;
  uint16_t flags;
  uint64_t session;
  uint64_t revision;
  uint64_t window_start;
  uint64_t anchor;
  uint64_t focus;
  uint64_t cursor;
  uint64_t viewport_first_block;
  /* Pixel scroll offset; Rust resolves it into a block index. */
  double scroll_offset_y;
  /* 字身 per line, measured from the real font; Rust returns 禁则 breaks. */
  double columns_em;
  uint32_t viewport_block_count;
  uint32_t text_len;
  /* Borrowed for the duration of the call only; the host never stores it. */
  const uint8_t *text;
} RefrainNativeRequest;
/* One anchored range in projection-window byte coordinates: an annotation
   (highlight or comment) or an undecided proposal, resolved by Rust against
   the current manuscript. kind: 1 = highlight, 2 = comment, 3 = proposal.
   Coordinates are u32 because the protocol already caps a document at 4 GiB
   (the overflow rule in encodeDispatchResponse). id is the source's durable
   identity (a 36-byte uuid string): the mark's actions name it. */
typedef struct RefrainNativeAnchorRange {
  uint32_t start;
  uint32_t end;
  uint32_t kind;
  uint8_t id[36];
} RefrainNativeAnchorRange;
typedef struct RefrainNativeResponse {
  uint32_t status;
  uint16_t protocol_version;
  uint16_t api_version;
  uint32_t capabilities;
  uint16_t action;
  uint16_t reserved;
  uint64_t session;
  uint64_t revision;
  uint64_t total_bytes;
  uint64_t total_blocks;
  uint64_t window_start;
  uint64_t first_block;
  uint32_t block_count;
  uint32_t text_len;
  uint32_t composition_len;
  /* Which grammar highlights this document, from Rust's DocumentFormat.
     0 is Markdown prose; the rest follow the enum's declaration order. The
     surface cannot infer it from the bytes: a fenced block inside Markdown
     and a whole .rs file both look like code to a scanner, and only the
     opening path knows which one this is. */
  uint32_t document_format;
  uint64_t selection_anchor;
  uint64_t selection_focus;
  uint64_t composition_start;
  uint64_t composition_end;
  uint64_t document_selection_start;
  uint64_t document_selection_end;
  /* Owned by the Rust session and valid until its next dispatch. */
  const uint8_t *text;
  /* CLREQ line-start offsets into text; same owner, same lifetime. */
  const uint32_t *line_starts;
  uint32_t line_start_count;
  /* Anchored ranges in window coordinates; same owner, same lifetime. */
  const RefrainNativeAnchorRange *anchor_ranges;
  uint32_t anchor_range_count;
} RefrainNativeResponse;
RefrainNativeResponse refrain_native_dispatch(RefrainNativeRequest request);
#endif
