// @generated by scripts/generate-native-protocol.ts; do not edit.

pub const PROTOCOL_VERSION: u16 = 6;
pub const API_VERSION: u16 = 1;
pub const CAPABILITY_MASK: u32 = 1;
pub const PROJECTION_BYTES: usize = 40960;
pub const EVENT_TEXT_BYTES: usize = 12000;
pub const DEFAULT_VIEWPORT_BLOCKS: u32 = 96;
pub const VIRTUAL_BLOCK_HEIGHT: f64 = 36.0;
pub const ANCHOR_RANGE_CAPACITY: usize = 512;
#[allow(dead_code)]
pub const PROTOCOL_FINGERPRINT: &str =
    "2be82cd976501fb657b6db59d738537fcaf6dba256c3e85ee74bc34d8a66c033";
pub const ERROR_PROTOCOL_MISMATCH: u32 = 1;
pub const ERROR_INVALID_REQUEST: u32 = 2;
pub const ERROR_UNKNOWN_SESSION: u32 = 3;
pub const ERROR_DOMAIN_REFUSAL: u32 = 4;
pub const ERROR_HOST_FAILURE: u32 = 5;
pub const ERROR_STALE_REVISION: u32 = 6;
pub const ACTION_HEALTH: u16 = 1;
pub const ACTION_OPEN_MANUSCRIPT: u16 = 2;
pub const ACTION_APPLY_INPUT: u16 = 3;
pub const ACTION_OBTAIN_PROJECTION: u16 = 4;
pub const ACTION_PROJECT: u16 = 5;
pub const ACTION_SCROLL_PROJECTION: u16 = 6;
pub const INPUT_SET_SELECTION: u16 = 1;
pub const INPUT_INSERT_TEXT: u16 = 2;
pub const INPUT_DELETE_BACKWARD: u16 = 3;
pub const INPUT_DELETE_FORWARD: u16 = 4;
pub const INPUT_DELETE_WORD_BACKWARD: u16 = 5;
pub const INPUT_DELETE_WORD_FORWARD: u16 = 6;
pub const INPUT_CLEAR: u16 = 7;
pub const INPUT_MOVE_CARET: u16 = 8;
pub const INPUT_SET_COMPOSITION: u16 = 9;
pub const INPUT_COMMIT_COMPOSITION: u16 = 10;
pub const INPUT_CANCEL_COMPOSITION: u16 = 11;
pub const INPUT_UNDO: u16 = 12;
pub const INPUT_SAVE: u16 = 13;
pub const INPUT_REVERT_TO: u16 = 14;
pub const CARET_PREVIOUS: u16 = 1;
pub const CARET_NEXT: u16 = 2;
pub const CARET_PREVIOUS_WORD: u16 = 3;
pub const CARET_NEXT_WORD: u16 = 4;
pub const CARET_START: u16 = 5;
pub const CARET_END: u16 = 6;
pub const CARET_EXTEND_FLAG: u16 = 0x100;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeRequest {
    pub protocol_version: u16,
    pub action: u16,
    pub input: u16,
    pub flags: u16,
    pub session: u64,
    pub revision: u64,
    pub window_start: u64,
    pub anchor: u64,
    pub focus: u64,
    pub cursor: u64,
    pub viewport_first_block: u64,
    /// Pixel scroll offset. Rust resolves it into a block index because only it
    /// knows the manuscript's block count.
    pub scroll_offset_y: f64,
    /// 字身 per line, measured by the platform from the real font. Rust turns
    /// it into 禁则-correct break offsets; zero means the caller wants no
    /// breaking (a probe, or a viewport with no width yet).
    pub columns_em: f64,
    pub viewport_block_count: u32,
    pub text_len: u32,
    /// Borrowed input bytes, valid only for the duration of one dispatch call.
    /// The host reads them once and never stores the pointer.
    pub text: *const u8,
}

/// One anchored range in projection-window byte coordinates: an annotation
/// (highlight or comment) or an undecided proposal, resolved against the
/// current manuscript. kind: 1 = highlight, 2 = comment, 3 = proposal.
/// Coordinates are u32 because the protocol already caps a document at 4 GiB.
/// id 是来源身份（36 字节 uuid 串）：印点上的动作按它点名。
#[repr(C)]
#[derive(Clone, Copy)]
pub struct AnchorRangeWire {
    pub start: u32,
    pub end: u32,
    pub kind: u32,
    pub id: [u8; 36],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeResponse {
    pub status: u32,
    pub protocol_version: u16,
    pub api_version: u16,
    pub capabilities: u32,
    pub action: u16,
    pub reserved: u16,
    pub session: u64,
    pub revision: u64,
    pub total_bytes: u64,
    pub total_blocks: u64,
    pub window_start: u64,
    pub first_block: u64,
    pub block_count: u32,
    pub text_len: u32,
    pub composition_len: u32,
    /// Which grammar highlights this document, from DocumentFormat.
    /// The surface cannot infer it from the bytes — a fenced block inside
    /// Markdown and a whole .rs file both scan as code — so the opening
    /// path, which is the only place that knows, sends it across.
    pub document_format: u32,
    pub selection_anchor: u64,
    pub selection_focus: u64,
    pub composition_start: u64,
    pub composition_end: u64,
    pub document_selection_start: u64,
    pub document_selection_end: u64,
    /// Projection bytes owned by the Rust session that produced them. Valid
    /// until that session handles its next dispatch; consumers read, never store.
    pub text: *const u8,
    /// Line-start byte offsets into the projection text, computed under CLREQ
    /// 禁则 by refrain_core::typeset. The SDK cannot wrap Chinese text — its
    /// only break opportunities are space and tab — so the view draws these
    /// rather than wrapping. Borrowed like the text: same owner and lifetime.
    pub line_starts: *const u32,
    pub line_start_count: u32,
    /// Anchored ranges in projection-window byte coordinates (annotations and
    /// undecided proposals), resolved against the current manuscript. Owned by
    /// the session like the text: valid until its next dispatch.
    pub anchor_ranges: *const AnchorRangeWire,
    pub anchor_range_count: u32,
}

impl RefrainNativeResponse {
    pub const fn empty(status: u32, action: u16) -> Self {
        Self {
            status,
            protocol_version: PROTOCOL_VERSION,
            api_version: API_VERSION,
            capabilities: CAPABILITY_MASK,
            action,
            reserved: 0,
            session: 0,
            revision: 0,
            total_bytes: 0,
            total_blocks: 0,
            window_start: 0,
            first_block: 0,
            block_count: 0,
            text_len: 0,
            composition_len: 0,
            document_format: 0,
            selection_anchor: 0,
            selection_focus: 0,
            composition_start: 0,
            composition_end: 0,
            document_selection_start: 0,
            document_selection_end: 0,
            text: std::ptr::null(),
            line_starts: std::ptr::null(),
            line_start_count: 0,
            anchor_ranges: std::ptr::null(),
            anchor_range_count: 0,
        }
    }
}
