// @generated by scripts/generate-native-protocol.ts; do not edit.

pub const PROTOCOL_VERSION: u16 = 1;
pub const HEALTH_API_VERSION: u16 = 1;
pub const CAPABILITY_TYPED_REQUESTS: u32 = 1;
pub const HEALTH_ERROR_PROTOCOL_MISMATCH: u32 = 1;

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefrainNativeHealth {
    pub protocol_version: u16,
    pub api_version: u16,
    pub capabilities: u32,
}

#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RefrainNativeHealthResult {
    pub status: u32,
    pub protocol_version: u16,
    pub api_version: u16,
    pub capabilities: u32,
}

pub const fn health() -> RefrainNativeHealth {
    RefrainNativeHealth {
        protocol_version: PROTOCOL_VERSION,
        api_version: HEALTH_API_VERSION,
        capabilities: CAPABILITY_TYPED_REQUESTS,
    }
}

pub const fn health_result(status: u32) -> RefrainNativeHealthResult {
    let health = health();
    RefrainNativeHealthResult {
        status,
        protocol_version: health.protocol_version,
        api_version: if status == 0 { health.api_version } else { 0 },
        capabilities: if status == 0 { health.capabilities } else { 0 },
    }
}
