// @generated by scripts/generate-native-protocol.ts; do not edit.

pub const PROTOCOL_VERSION: u16 = 2;
pub const API_VERSION: u16 = 1;
pub const CAPABILITY_MASK: u32 = 1;
pub const PROJECTION_BYTES: usize = 40960;
pub const EVENT_TEXT_BYTES: usize = 12000;
pub const DEFAULT_VIEWPORT_BLOCKS: u32 = 96;
#[allow(dead_code)]
pub const PROTOCOL_FINGERPRINT: &str =
    "f21e1dcfa20d362a6744371f720fa945b36cf508c772d639d5b7c6a53d672aa1";
pub const ERROR_PROTOCOL_MISMATCH: u32 = 1;
pub const ERROR_INVALID_REQUEST: u32 = 2;
pub const ERROR_UNKNOWN_SESSION: u32 = 3;
pub const ERROR_DOMAIN_REFUSAL: u32 = 4;
pub const ERROR_HOST_FAILURE: u32 = 5;
pub const ERROR_STALE_REVISION: u32 = 6;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeRequest {
    pub protocol_version: u16,
    pub action: u16,
    pub input: u16,
    pub flags: u16,
    pub session: u64,
    pub revision: u64,
    pub window_start: u64,
    pub anchor: u64,
    pub focus: u64,
    pub cursor: u64,
    pub viewport_first_block: u64,
    pub viewport_block_count: u32,
    pub text_len: u32,
    pub text: [u8; EVENT_TEXT_BYTES],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeResponse {
    pub status: u32,
    pub protocol_version: u16,
    pub api_version: u16,
    pub capabilities: u32,
    pub action: u16,
    pub reserved: u16,
    pub session: u64,
    pub revision: u64,
    pub total_bytes: u64,
    pub total_blocks: u64,
    pub window_start: u64,
    pub first_block: u64,
    pub block_count: u32,
    pub text_len: u32,
    pub composition_len: u32,
    pub projection_reserved: u32,
    pub selection_anchor: u64,
    pub selection_focus: u64,
    pub composition_start: u64,
    pub composition_end: u64,
    pub composition_cursor: u64,
    pub text: [u8; PROJECTION_BYTES],
    pub composition: [u8; EVENT_TEXT_BYTES],
}

impl RefrainNativeResponse {
    pub const fn empty(status: u32, action: u16) -> Self {
        Self {
            status,
            protocol_version: PROTOCOL_VERSION,
            api_version: API_VERSION,
            capabilities: CAPABILITY_MASK,
            action,
            reserved: 0,
            session: 0,
            revision: 0,
            total_bytes: 0,
            total_blocks: 0,
            window_start: 0,
            first_block: 0,
            block_count: 0,
            text_len: 0,
            composition_len: 0,
            projection_reserved: 0,
            selection_anchor: 0,
            selection_focus: 0,
            composition_start: 0,
            composition_end: 0,
            composition_cursor: 0,
            text: [0; PROJECTION_BYTES],
            composition: [0; EVENT_TEXT_BYTES],
        }
    }
}
