// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the RefRain contributors
// @generated by scripts/generate-native-protocol.ts; do not edit.
//! 项目答复的线上形状，Rust 这一侧。
//!
//! 每个成员自己把小端字节推进缓冲，所以这里**不需要 `unsafe`，也不需要
//! `repr(C)`**：字节顺序由 `protocol/host.json` 那张表决定，而 Zig 侧的
//! `extern struct` 由同一张表排布——两者一起改，或者一起不改。
#![allow(
    dead_code,
    reason = "generated: not every reply shape has a reader yet"
)]

pub const MAGIC: u32 = 0x5257_4652;
pub const PROTOCOL_FINGERPRINT: &str =
    "2be82cd976501fb657b6db59d738537fcaf6dba256c3e85ee74bc34d8a66c033";
pub const HEADER_BYTES: usize = 16;

/// 一段字节在缓冲里的位置。
#[derive(Debug, Clone, Copy, Default)]
pub struct Str {
    pub off: u32,
    pub len: u32,
}

/// 一列定长行在缓冲里的位置。`len` 是行数，不是字节数。
#[derive(Debug, Clone, Copy, Default)]
pub struct Rows {
    pub off: u32,
    pub len: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum Kind {
    Cancelled = 1,
    Opened = 2,
    DocumentOpened = 3,
    Imported = 4,
    Page = 5,
    Documents = 6,
    Blocks = 7,
    DocumentBlocks = 8,
    Materials = 9,
    Deleted = 10,
    DisclosureSet = 11,
    Config = 12,
    Kara = 13,
    Host = 14,
    History = 15,
    Annotations = 16,
    Harnesses = 17,
    Dispatched = 18,
    Proposals = 19,
    Decided = 20,
    Collected = 21,
    Mailbox = 22,
    DispatchPreview = 23,
    MaterialDrafts = 24,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum DocumentRole {
    #[default]
    Unknown = 0,
    Chapter = 1,
    Document = 2,
    Material = 3,
}

impl DocumentRole {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::Chapter,
            2 => Self::Document,
            3 => Self::Material,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum RunProgress {
    #[default]
    Unknown = 0,
    Queued = 1,
    Authorized = 2,
    Launching = 3,
    Dispatched = 4,
    Completed = 5,
    Failed = 6,
    Cancelled = 7,
}

impl RunProgress {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::Queued,
            2 => Self::Authorized,
            3 => Self::Launching,
            4 => Self::Dispatched,
            5 => Self::Completed,
            6 => Self::Failed,
            7 => Self::Cancelled,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum Disclosure {
    #[default]
    Retrievable = 0,
    OutlineOnly = 1,
    Full = 2,
    Unknown = 3,
}

impl Disclosure {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Retrievable,
            1 => Self::OutlineOnly,
            2 => Self::Full,
            3 => Self::Unknown,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HarnessState {
    #[default]
    Unknown = 0,
    Ready = 1,
    NotInstalled = 2,
    Unreadable = 3,
}

impl HarnessState {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::Ready,
            2 => Self::NotInstalled,
            3 => Self::Unreadable,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HarnessTier {
    #[default]
    None = 0,
    File = 1,
    Launch = 2,
    Usage = 3,
}

impl HarnessTier {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::None,
            1 => Self::File,
            2 => Self::Launch,
            3 => Self::Usage,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HarnessSkill {
    #[default]
    Unknown = 0,
    None = 1,
    Current = 2,
    Stale = 3,
}

impl HarnessSkill {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::None,
            2 => Self::Current,
            3 => Self::Stale,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum MailboxBox {
    #[default]
    Unknown = 0,
    Draft = 1,
    Unread = 2,
    Done = 3,
}

impl MailboxBox {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::Draft,
            2 => Self::Unread,
            3 => Self::Done,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum PersonaMode {
    #[default]
    None = 0,
    Work = 1,
    Cosplay = 2,
    Unknown = 3,
}

impl PersonaMode {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::None,
            1 => Self::Work,
            2 => Self::Cosplay,
            3 => Self::Unknown,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum DecisionState {
    #[default]
    None = 0,
    Durable = 1,
    BodyDurable = 2,
    Conflict = 3,
}

impl DecisionState {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::None,
            1 => Self::Durable,
            2 => Self::BodyDurable,
            3 => Self::Conflict,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum CollectState {
    #[default]
    None = 0,
    Waiting = 1,
    Completed = 2,
    Failed = 3,
}

impl CollectState {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::None,
            1 => Self::Waiting,
            2 => Self::Completed,
            3 => Self::Failed,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum KaraState {
    #[default]
    Off = 0,
    Entering = 1,
    Writing = 2,
    Reviewing = 3,
    Away = 4,
    Leaving = 5,
}

impl KaraState {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Off,
            1 => Self::Entering,
            2 => Self::Writing,
            3 => Self::Reviewing,
            4 => Self::Away,
            5 => Self::Leaving,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum Tokens {
    #[default]
    Unknown = 0,
    Actual = 1,
    Estimated = 2,
}

impl Tokens {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Unknown,
            1 => Self::Actual,
            2 => Self::Estimated,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum PanelMaterial {
    #[default]
    Solid = 0,
    Acrylic = 1,
    Liquid = 2,
}

impl PanelMaterial {
    /// 认不出的码落到第一个变体（各表的第一个都是「未知」或「默认」）——
    /// 一个读不懂的值被当成某个已知值，比说不出来危险得多。
    #[must_use]
    pub fn from_code(code: u8) -> Self {
        match code {
            0 => Self::Solid,
            1 => Self::Acrylic,
            2 => Self::Liquid,
            _ => Self::default(),
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DocumentRow {
    pub path: Str,
    pub title: Str,
    pub role: DocumentRole,
}

impl WireRow for DocumentRow {
    const BYTES: usize = 20;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.path);
        push_str_field(out, self.title);
        out.push(self.role as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            path: read_str(bytes, 0)?,
            title: read_str(bytes, 8)?,
            role: DocumentRole::from_code(read_u8(bytes, 16)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct RunRow {
    pub id: Str,
    pub document: Str,
    pub workspace: Str,
    pub failure: Str,
    pub progress: RunProgress,
    pub needs_recovery: bool,
}

impl WireRow for RunRow {
    const BYTES: usize = 36;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.document);
        push_str_field(out, self.workspace);
        push_str_field(out, self.failure);
        out.push(self.progress as u8);
        out.push(u8::from(self.needs_recovery));
        out.extend_from_slice(&[0u8; 2]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            document: read_str(bytes, 8)?,
            workspace: read_str(bytes, 16)?,
            failure: read_str(bytes, 24)?,
            progress: RunProgress::from_code(read_u8(bytes, 32)?),
            needs_recovery: read_u8(bytes, 33)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ProposalRow {
    pub id: Str,
    pub scope: Str,
    pub before_text: Str,
    pub after_text: Str,
    pub staged: bool,
}

impl WireRow for ProposalRow {
    const BYTES: usize = 36;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.scope);
        push_str_field(out, self.before_text);
        push_str_field(out, self.after_text);
        out.push(u8::from(self.staged));
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            scope: read_str(bytes, 8)?,
            before_text: read_str(bytes, 16)?,
            after_text: read_str(bytes, 24)?,
            staged: read_u8(bytes, 32)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct HitRow {
    pub path: Str,
    pub text: Str,
    pub ordinal: u32,
    pub block: bool,
}

impl WireRow for HitRow {
    const BYTES: usize = 24;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.path);
        push_str_field(out, self.text);
        push_u32(out, self.ordinal);
        out.push(u8::from(self.block));
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            path: read_str(bytes, 0)?,
            text: read_str(bytes, 8)?,
            ordinal: read_u32(bytes, 16)?,
            block: read_u8(bytes, 20)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DeskBlockRow {
    pub id: Str,
    pub kind: Str,
    pub peek: Str,
    pub ordinal: u32,
    pub chars: u32,
}

impl WireRow for DeskBlockRow {
    const BYTES: usize = 32;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.kind);
        push_str_field(out, self.peek);
        push_u32(out, self.ordinal);
        push_u32(out, self.chars);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            kind: read_str(bytes, 8)?,
            peek: read_str(bytes, 16)?,
            ordinal: read_u32(bytes, 24)?,
            chars: read_u32(bytes, 28)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MaterialRow {
    pub path: Str,
    pub disclosure: Disclosure,
}

impl WireRow for MaterialRow {
    const BYTES: usize = 12;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.path);
        out.push(self.disclosure as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            path: read_str(bytes, 0)?,
            disclosure: Disclosure::from_code(read_u8(bytes, 8)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MaterialDraftRow {
    pub id: Str,
    pub title: Str,
    pub kind: Str,
    pub body: Str,
}

impl WireRow for MaterialDraftRow {
    const BYTES: usize = 32;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.title);
        push_str_field(out, self.kind);
        push_str_field(out, self.body);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            title: read_str(bytes, 8)?,
            kind: read_str(bytes, 16)?,
            body: read_str(bytes, 24)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct HarnessRow {
    pub id: Str,
    pub program: Str,
    pub version: Str,
    pub state: HarnessState,
    pub tier: HarnessTier,
    pub skill: HarnessSkill,
}

impl WireRow for HarnessRow {
    const BYTES: usize = 28;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.program);
        push_str_field(out, self.version);
        out.push(self.state as u8);
        out.push(self.tier as u8);
        out.push(self.skill as u8);
        out.extend_from_slice(&[0u8; 1]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            program: read_str(bytes, 8)?,
            version: read_str(bytes, 16)?,
            state: HarnessState::from_code(read_u8(bytes, 24)?),
            tier: HarnessTier::from_code(read_u8(bytes, 25)?),
            skill: HarnessSkill::from_code(read_u8(bytes, 26)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ChangeRow {
    pub id: Str,
    pub cause: Str,
    pub ordinal: u32,
    pub undone: bool,
}

impl WireRow for ChangeRow {
    const BYTES: usize = 24;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.cause);
        push_u32(out, self.ordinal);
        out.push(u8::from(self.undone));
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            cause: read_str(bytes, 8)?,
            ordinal: read_u32(bytes, 16)?,
            undone: read_u8(bytes, 20)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MailboxRow {
    pub id: Str,
    pub document: Str,
    pub scope: Str,
    pub before_text: Str,
    pub after_text: Str,
    pub rank: u32,
    pub box_name: MailboxBox,
    pub pinned: bool,
    pub ranked: bool,
}

impl WireRow for MailboxRow {
    const BYTES: usize = 48;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.document);
        push_str_field(out, self.scope);
        push_str_field(out, self.before_text);
        push_str_field(out, self.after_text);
        push_u32(out, self.rank);
        out.push(self.box_name as u8);
        out.push(u8::from(self.pinned));
        out.push(u8::from(self.ranked));
        out.extend_from_slice(&[0u8; 1]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            document: read_str(bytes, 8)?,
            scope: read_str(bytes, 16)?,
            before_text: read_str(bytes, 24)?,
            after_text: read_str(bytes, 32)?,
            rank: read_u32(bytes, 40)?,
            box_name: MailboxBox::from_code(read_u8(bytes, 44)?),
            pinned: read_u8(bytes, 45)? != 0,
            ranked: read_u8(bytes, 46)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ManifestRow {
    pub section: Str,
    pub source: Str,
    pub bytes: u32,
    pub tokens: Tokens,
}

impl WireRow for ManifestRow {
    const BYTES: usize = 24;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.section);
        push_str_field(out, self.source);
        push_u32(out, self.bytes);
        out.push(self.tokens as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            section: read_str(bytes, 0)?,
            source: read_str(bytes, 8)?,
            bytes: read_u32(bytes, 16)?,
            tokens: Tokens::from_code(read_u8(bytes, 20)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct AgentRow {
    pub id: Str,
    pub name: Str,
    pub persona_body: Str,
    pub connection_id: Str,
    pub argv_count: u32,
    pub mode: PersonaMode,
}

impl WireRow for AgentRow {
    const BYTES: usize = 40;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.id);
        push_str_field(out, self.name);
        push_str_field(out, self.persona_body);
        push_str_field(out, self.connection_id);
        push_u32(out, self.argv_count);
        out.push(self.mode as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            id: read_str(bytes, 0)?,
            name: read_str(bytes, 8)?,
            persona_body: read_str(bytes, 16)?,
            connection_id: read_str(bytes, 24)?,
            argv_count: read_u32(bytes, 32)?,
            mode: PersonaMode::from_code(read_u8(bytes, 36)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ConnectionRow {
    pub adapter: Str,
    pub executable: Str,
    pub argv_count: u32,
}

impl WireRow for ConnectionRow {
    const BYTES: usize = 20;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.adapter);
        push_str_field(out, self.executable);
        push_u32(out, self.argv_count);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            adapter: read_str(bytes, 0)?,
            executable: read_str(bytes, 8)?,
            argv_count: read_u32(bytes, 16)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct AnnotationRow {
    pub quote: Str,
    pub body: Str,
    pub comment: bool,
}

impl WireRow for AnnotationRow {
    const BYTES: usize = 20;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.quote);
        push_str_field(out, self.body);
        out.push(u8::from(self.comment));
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            quote: read_str(bytes, 0)?,
            body: read_str(bytes, 8)?,
            comment: read_u8(bytes, 16)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct CancelledHead {
    pub unused: u32,
}

impl WireRow for CancelledHead {
    const BYTES: usize = 4;

    fn write(&self, out: &mut Vec<u8>) {
        push_u32(out, self.unused);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            unused: read_u32(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct OpenedHead {
    pub root_id: Str,
    pub document_cursor: Str,
    pub document_total: u32,
    pub documents: Rows,
}

impl WireRow for OpenedHead {
    const BYTES: usize = 28;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.root_id);
        push_str_field(out, self.document_cursor);
        push_u32(out, self.document_total);
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            root_id: read_str(bytes, 0)?,
            document_cursor: read_str(bytes, 8)?,
            document_total: read_u32(bytes, 16)?,
            documents: read_rows(bytes, 20)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DocumentOpenedHead {
    pub root_id: Str,
}

impl WireRow for DocumentOpenedHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.root_id);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            root_id: read_str(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ImportedHead {
    pub documents: Rows,
}

impl WireRow for ImportedHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            documents: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct PageHead {
    pub document_cursor: Str,
    pub document_total: u32,
    pub documents: Rows,
}

impl WireRow for PageHead {
    const BYTES: usize = 20;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.document_cursor);
        push_u32(out, self.document_total);
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            document_cursor: read_str(bytes, 0)?,
            document_total: read_u32(bytes, 8)?,
            documents: read_rows(bytes, 12)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DocumentsHead {
    pub documents: Rows,
}

impl WireRow for DocumentsHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            documents: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct BlocksHead {
    pub hits: Rows,
}

impl WireRow for BlocksHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.hits);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            hits: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DocumentBlocksHead {
    pub blocks: Rows,
    pub next: u32,
}

impl WireRow for DocumentBlocksHead {
    const BYTES: usize = 12;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.blocks);
        push_u32(out, self.next);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            blocks: read_rows(bytes, 0)?,
            next: read_u32(bytes, 8)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MaterialsHead {
    pub materials: Rows,
    pub truncated: bool,
}

impl WireRow for MaterialsHead {
    const BYTES: usize = 12;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.materials);
        out.push(u8::from(self.truncated));
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            materials: read_rows(bytes, 0)?,
            truncated: read_u8(bytes, 8)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DeletedHead {
    pub documents: Rows,
}

impl WireRow for DeletedHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            documents: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DisclosureSetHead {
    pub documents: Rows,
}

impl WireRow for DisclosureSetHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.documents);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            documents: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ConfigHead {
    pub theme: Str,
    pub font_latin: Str,
    pub font_chinese: Str,
    pub font_japanese: Str,
    pub text_size_tenths_px: u32,
    pub measure_tenths_em: u32,
    pub line_height_percent: u32,
    pub agents: Rows,
    pub connections: Rows,
    pub panel_material: PanelMaterial,
}

impl WireRow for ConfigHead {
    const BYTES: usize = 64;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.theme);
        push_str_field(out, self.font_latin);
        push_str_field(out, self.font_chinese);
        push_str_field(out, self.font_japanese);
        push_u32(out, self.text_size_tenths_px);
        push_u32(out, self.measure_tenths_em);
        push_u32(out, self.line_height_percent);
        push_rows_field(out, self.agents);
        push_rows_field(out, self.connections);
        out.push(self.panel_material as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            theme: read_str(bytes, 0)?,
            font_latin: read_str(bytes, 8)?,
            font_chinese: read_str(bytes, 16)?,
            font_japanese: read_str(bytes, 24)?,
            text_size_tenths_px: read_u32(bytes, 32)?,
            measure_tenths_em: read_u32(bytes, 36)?,
            line_height_percent: read_u32(bytes, 40)?,
            agents: read_rows(bytes, 44)?,
            connections: read_rows(bytes, 52)?,
            panel_material: PanelMaterial::from_code(read_u8(bytes, 60)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct KaraHead {
    pub return_tail: Str,
    pub interrupt: Str,
    pub queued_mask: u32,
    pub state: KaraState,
    pub card: bool,
}

impl WireRow for KaraHead {
    const BYTES: usize = 24;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.return_tail);
        push_str_field(out, self.interrupt);
        push_u32(out, self.queued_mask);
        out.push(self.state as u8);
        out.push(u8::from(self.card));
        out.extend_from_slice(&[0u8; 2]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            return_tail: read_str(bytes, 0)?,
            interrupt: read_str(bytes, 8)?,
            queued_mask: read_u32(bytes, 16)?,
            state: KaraState::from_code(read_u8(bytes, 20)?),
            card: read_u8(bytes, 21)? != 0,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct HostHead {
    pub runs: Rows,
    pub run_total: u32,
}

impl WireRow for HostHead {
    const BYTES: usize = 12;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.runs);
        push_u32(out, self.run_total);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            runs: read_rows(bytes, 0)?,
            run_total: read_u32(bytes, 8)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct HistoryHead {
    pub changes: Rows,
}

impl WireRow for HistoryHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.changes);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            changes: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct AnnotationsHead {
    pub annotations: Rows,
}

impl WireRow for AnnotationsHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.annotations);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            annotations: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct HarnessesHead {
    pub harnesses: Rows,
}

impl WireRow for HarnessesHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.harnesses);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            harnesses: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DispatchedHead {
    pub run_count: u32,
}

impl WireRow for DispatchedHead {
    const BYTES: usize = 4;

    fn write(&self, out: &mut Vec<u8>) {
        push_u32(out, self.run_count);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            run_count: read_u32(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct ProposalsHead {
    pub proposals: Rows,
    pub staged_count: u32,
}

impl WireRow for ProposalsHead {
    const BYTES: usize = 12;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.proposals);
        push_u32(out, self.staged_count);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            proposals: read_rows(bytes, 0)?,
            staged_count: read_u32(bytes, 8)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DecidedHead {
    pub state: DecisionState,
}

impl WireRow for DecidedHead {
    const BYTES: usize = 4;

    fn write(&self, out: &mut Vec<u8>) {
        out.push(self.state as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            state: DecisionState::from_code(read_u8(bytes, 0)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct CollectedHead {
    pub state: CollectState,
}

impl WireRow for CollectedHead {
    const BYTES: usize = 4;

    fn write(&self, out: &mut Vec<u8>) {
        out.push(self.state as u8);
        out.extend_from_slice(&[0u8; 3]);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            state: CollectState::from_code(read_u8(bytes, 0)?),
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MailboxHead {
    pub entries: Rows,
}

impl WireRow for MailboxHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.entries);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            entries: read_rows(bytes, 0)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct DispatchPreviewHead {
    pub digest: Str,
    pub prefix_bytes: u32,
    pub manifest: Rows,
}

impl WireRow for DispatchPreviewHead {
    const BYTES: usize = 20;

    fn write(&self, out: &mut Vec<u8>) {
        push_str_field(out, self.digest);
        push_u32(out, self.prefix_bytes);
        push_rows_field(out, self.manifest);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            digest: read_str(bytes, 0)?,
            prefix_bytes: read_u32(bytes, 8)?,
            manifest: read_rows(bytes, 12)?,
        })
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub struct MaterialDraftsHead {
    pub drafts: Rows,
}

impl WireRow for MaterialDraftsHead {
    const BYTES: usize = 8;

    fn write(&self, out: &mut Vec<u8>) {
        push_rows_field(out, self.drafts);
    }

    fn read(bytes: &[u8]) -> Option<Self> {
        Some(Self {
            drafts: read_rows(bytes, 0)?,
        })
    }
}

/// 一条答复的缓冲。
///
/// 头留在最前面，行与字节追加在它后面，最后头被填回去——所以 `Rows` 与 `Str`
/// 的偏移在写下它们的那一刻就已经是最终值，不需要第二遍修补。
pub struct Writer {
    buf: Vec<u8>,
    kind: Kind,
}

impl Writer {
    pub fn new(kind: Kind, head_bytes: usize) -> Self {
        let mut buf = vec![0u8; HEADER_BYTES];
        buf.resize(HEADER_BYTES.saturating_add(head_bytes), 0);
        Self { buf, kind }
    }

    /// 追加一段文本。空文本不占缓冲——一个 {0,0} 的 `Str` 读出来就是空。
    pub fn text(&mut self, value: &str) -> Str {
        if value.is_empty() {
            return Str::default();
        }
        let off = u32::try_from(self.buf.len()).unwrap_or(0);
        let len = u32::try_from(value.len()).unwrap_or(0);
        if off == 0 || len == 0 {
            return Str::default();
        }
        self.buf.extend_from_slice(value.as_bytes());
        Str { off, len }
    }

    /// 追加一列行，先对齐到四字节——Zig 侧按对齐取切片，对不齐整列作废。
    pub fn rows<T: WireRow>(&mut self, rows: &[T]) -> Rows {
        while !self.buf.len().is_multiple_of(4) {
            self.buf.push(0);
        }
        let off = u32::try_from(self.buf.len()).unwrap_or(0);
        let len = u32::try_from(rows.len()).unwrap_or(0);
        if off == 0 {
            return Rows::default();
        }
        for row in rows {
            row.write(&mut self.buf);
        }
        Rows { off, len }
    }

    /// 填回头并交出整段缓冲。
    pub fn finish<H: WireRow>(mut self, head: &H) -> Vec<u8> {
        let mut encoded = Vec::with_capacity(H::BYTES);
        head.write(&mut encoded);
        let end = HEADER_BYTES.saturating_add(encoded.len());
        if let Some(slot) = self.buf.get_mut(HEADER_BYTES..end) {
            slot.copy_from_slice(&encoded);
        }
        let total = u32::try_from(self.buf.len()).unwrap_or(0);
        let mut header = Vec::with_capacity(HEADER_BYTES);
        push_u32(&mut header, MAGIC);
        push_u32(&mut header, self.kind as u32);
        push_u32(&mut header, total);
        push_u32(&mut header, 0);
        if let Some(slot) = self.buf.get_mut(0..HEADER_BYTES) {
            slot.copy_from_slice(&header);
        }
        self.buf
    }
}

/// 一个能把自己写成线上字节、也能从线上字节读回来的形状。
///
/// 读回来这一半是给**这一侧自己的测试**用的：把编码器的产物读回来断言，
/// 比按字节偏移手抄一份期望值可靠——手抄的那份会在 schema 变动时静默漂开。
pub trait WireRow: Sized {
    const BYTES: usize;
    fn write(&self, out: &mut Vec<u8>);
    fn read(bytes: &[u8]) -> Option<Self>;
}

/// 一段线上答复的读法，与 Zig 的 `wire.Reply` 同规。
#[derive(Debug, Clone, Copy)]
pub struct Reply<'a> {
    bytes: &'a [u8],
}

impl<'a> Reply<'a> {
    pub fn new(bytes: &'a [u8]) -> Self {
        Self { bytes }
    }

    fn stated_len(&self) -> Option<usize> {
        if read_u32(self.bytes, 0)? != MAGIC {
            return None;
        }
        let stated = usize::try_from(read_u32(self.bytes, 8)?).ok()?;
        (stated <= self.bytes.len()).then_some(stated)
    }

    /// 这条答复自称的种类码。读不出就是 0。
    #[must_use]
    pub fn kind_code(&self) -> u32 {
        self.stated_len()
            .and_then(|_| read_u32(self.bytes, 4))
            .unwrap_or(0)
    }

    /// 这条答复的头。
    #[must_use]
    pub fn head<H: WireRow>(&self) -> Option<H> {
        let end = HEADER_BYTES.checked_add(H::BYTES)?;
        (end <= self.stated_len()?).then_some(())?;
        H::read(self.bytes.get(HEADER_BYTES..end)?)
    }

    /// 一段文本。越界交出空，不交相邻答复的内容。
    #[must_use]
    pub fn text(&self, value: Str) -> &'a str {
        let start = usize::try_from(value.off).unwrap_or(0);
        let end = start.saturating_add(usize::try_from(value.len).unwrap_or(0));
        match self.stated_len() {
            Some(stated) if end <= stated => self
                .bytes
                .get(start..end)
                .and_then(|raw| std::str::from_utf8(raw).ok()),
            _ => None,
        }
        .unwrap_or_default()
    }

    /// 一列行。对不齐或越界都交出空列，不交半行。
    #[must_use]
    pub fn rows<R: WireRow>(&self, value: Rows) -> Vec<R> {
        let start = usize::try_from(value.off).unwrap_or(0);
        let count = usize::try_from(value.len).unwrap_or(0);
        let Some(stated) = self.stated_len() else {
            return Vec::new();
        };
        let mut out = Vec::with_capacity(count);
        for index in 0..count {
            let Some(at) = index
                .checked_mul(R::BYTES)
                .and_then(|off| start.checked_add(off))
            else {
                return out;
            };
            let Some(end) = at.checked_add(R::BYTES) else {
                return out;
            };
            if end > stated {
                return out;
            }
            match self.bytes.get(at..end).and_then(R::read) {
                Some(row) => out.push(row),
                None => return out,
            }
        }
        out
    }
}

fn read_u8(bytes: &[u8], at: usize) -> Option<u8> {
    bytes.get(at).copied()
}

fn read_u32(bytes: &[u8], at: usize) -> Option<u32> {
    let end = at.checked_add(4)?;
    Some(u32::from_le_bytes(bytes.get(at..end)?.try_into().ok()?))
}

fn read_str(bytes: &[u8], at: usize) -> Option<Str> {
    Some(Str {
        off: read_u32(bytes, at)?,
        len: read_u32(bytes, at.checked_add(4)?)?,
    })
}

fn read_rows(bytes: &[u8], at: usize) -> Option<Rows> {
    Some(Rows {
        off: read_u32(bytes, at)?,
        len: read_u32(bytes, at.checked_add(4)?)?,
    })
}

fn push_u32(out: &mut Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_le_bytes());
}

fn push_str_field(out: &mut Vec<u8>, value: Str) {
    push_u32(out, value.off);
    push_u32(out, value.len);
}

fn push_rows_field(out: &mut Vec<u8>, value: Rows) {
    push_u32(out, value.off);
    push_u32(out, value.len);
}
