//! Binding generation.
//!
//! Generation runs as a test rather than as a build script or an extra binary:
//! it needs no network, it fails the suite when it drifts, and `bun run
//! generate` is a thin wrapper over it. The emitted files are checked in, and
//! `verify:bridge` fails when regenerating changes a byte — that is what makes
//! a hand edit to `src/generated/` detectable (SPEC 6.4).

#[cfg(feature = "generate-bindings")]
#[test]
fn generate_bindings() {
    use specta_typescript::Typescript;

    let header = "// Generated by `bun run generate`. Do not edit by hand.\n\
                  // `verify:bridge` fails the build when this file drifts from the Rust types.\n";

    refrain_desktop_lib::builder()
        .export(
            Typescript::default().header(header),
            "../src/generated/bindings.gen.ts",
        )
        .expect("failed to export TypeScript bindings");
}
