//! Binding generation.
//!
//! Generation runs as a test rather than as a build script or an extra binary:
//! it needs no network, it fails the suite when it drifts, and `bun run
//! generate` is a thin wrapper over it. The emitted files are checked in, and
//! `verify:bridge` fails when regenerating changes a byte — that is what makes
//! a hand edit to `src/generated/` detectable (SPEC 6.4).

#[cfg(feature = "generate-bindings")]
#[test]
fn generate_bindings() {
    use specta_typescript::Typescript;
    use std::fs;

    const OUTPUT: &str = "../src/generated/bindings.gen.ts";
    let header = "// Generated by `bun run generate`. Do not edit by hand.\n\
                  // `verify:bridge` fails the build when this file drifts from the Rust types.\n";

    refrain_desktop_lib::builder()
        .export(Typescript::default().header(header), OUTPUT)
        .expect("failed to export TypeScript bindings");

    // specta preserves whitespace around documented union variants. Normalise
    // at the generation boundary so every consumer gets one stable artifact;
    // asking callers to run a formatter would make raw regeneration drift.
    let emitted = fs::read_to_string(OUTPUT).expect("failed to read generated TypeScript bindings");
    let normalised = emitted
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";
    if normalised != emitted {
        fs::write(OUTPUT, normalised).expect("failed to normalise generated TypeScript bindings");
    }
}
