import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface ProtocolError {
  readonly name: string;
  readonly code: number;
}

interface ProtocolSchema {
  readonly schemaVersion: number;
  readonly magic: string;
  readonly service: string;
  readonly protocolVersion: number;
  readonly apiVersion: number;
  readonly capabilityMask: number;

  readonly layout: {
    readonly projectionBytes: number;
    readonly eventTextBytes: number;
    readonly defaultViewportBlocks: number;
    readonly virtualBlockHeight: number;
  };
  readonly errors: readonly ProtocolError[];
}

interface Output {
  readonly path: string;
  readonly content: string;
}

const root = resolve(import.meta.dir, "..");
const schemaPath = resolve(root, "apps/native/protocol/host.json");
const raw = readFileSync(schemaPath, "utf8");
const parsed: unknown = JSON.parse(raw);
const schema = protocolSchema(parsed);
const fingerprint = createHash("sha256").update(raw).digest("hex");
const outputs: readonly Output[] = [
  {
    path: resolve(root, "apps/native/host/include/refrain_native.h"),
    content: renderHeader(schema, fingerprint),
  },
  {
    path: resolve(root, "apps/native/host/src/protocol.rs"),
    content: renderRust(schema, fingerprint),
  },
  {
    path: resolve(root, "apps/native/src/generated/protocol.zig"),
    content: renderZig(schema, fingerprint),
  },
  {
    path: resolve(root, "apps/native/src/generated/protocol.ts"),
    content: renderTypeScript(schema, fingerprint),
  },
];

const check = process.argv.includes("--check");
let stale = false;
for (const output of outputs) {
  if (check) {
    if (readFileSync(output.path, "utf8") !== output.content) {
      console.error(`stale generated protocol: ${output.path}`);
      stale = true;
    }
  } else {
    writeFileSync(output.path, output.content);
  }
}
if (stale) process.exit(1);

function protocolSchema(value: unknown): ProtocolSchema {
  if (!isRecord(value) || !isRecord(value.layout) || !Array.isArray(value.errors)) {
    throw new Error("native protocol schema must declare layout and errors");
  }
  const errors: ProtocolError[] = value.errors.map((error: unknown) => {
    if (!isRecord(error) || typeof error.name !== "string" || typeof error.code !== "number") {
      throw new Error("native protocol error entries require string name and numeric code");
    }
    return { name: error.name, code: integer(error.code, `error ${error.name}`) };
  });
  const layout = value.layout;
  const result: ProtocolSchema = {
    schemaVersion: integer(value.schemaVersion, "schemaVersion"),
    magic: string(value.magic, "magic"),
    service: string(value.service, "service"),
    protocolVersion: integer(value.protocolVersion, "protocolVersion"),
    apiVersion: integer(value.apiVersion, "apiVersion"),
    capabilityMask: integer(value.capabilityMask, "capabilityMask"),

    layout: {
      projectionBytes: integer(layout.projectionBytes, "layout.projectionBytes"),
      eventTextBytes: integer(layout.eventTextBytes, "layout.eventTextBytes"),
      defaultViewportBlocks: integer(layout.defaultViewportBlocks, "layout.defaultViewportBlocks"),
      virtualBlockHeight: integer(layout.virtualBlockHeight, "layout.virtualBlockHeight"),
    },
    errors,
  };
  if (result.magic.length !== 4) throw new Error("native protocol magic must be four ASCII bytes");
  if (new Set(errors.map((error) => error.code)).size !== errors.length) {
    throw new Error("native protocol error codes must be unique");
  }
  return result;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function integer(value: unknown, name: string): number {
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    throw new Error(`${name} must be a non-negative integer`);
  }
  return value;
}

function string(value: unknown, name: string): string {
  if (typeof value !== "string") throw new Error(`${name} must be a string`);
  return value;
}

function snake(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function upperSnake(name: string): string {
  return snake(name).toUpperCase();
}

function magicBytes(magic: string): string {
  return [...magic].map((character) => character.charCodeAt(0)).join(", ");
}

function renderHeader(schema: ProtocolSchema, hash: string): string {
  const errors = schema.errors
    .map((error) => `#define REFRAIN_ERROR_${upperSnake(error.name)} ${error.code}`)
    .join("\n");
  return `/* @generated by scripts/generate-native-protocol.ts; do not edit. */
#ifndef REFRAIN_NATIVE_H
#define REFRAIN_NATIVE_H
#include <stdint.h>
#define REFRAIN_PROTOCOL_VERSION ${schema.protocolVersion}
#define REFRAIN_API_VERSION ${schema.apiVersion}
#define REFRAIN_CAPABILITY_MASK ${schema.capabilityMask}
#define REFRAIN_PROJECTION_BYTES ${schema.layout.projectionBytes}
#define REFRAIN_EVENT_TEXT_BYTES ${schema.layout.eventTextBytes}
#define REFRAIN_DEFAULT_VIEWPORT_BLOCKS ${schema.layout.defaultViewportBlocks}
#define REFRAIN_VIRTUAL_BLOCK_HEIGHT ${schema.layout.virtualBlockHeight}
#define REFRAIN_PROTOCOL_FINGERPRINT "${hash}"
${errors}
typedef struct RefrainNativeRequest {
  uint16_t protocol_version;
  uint16_t action;
  uint16_t input;
  uint16_t flags;
  uint64_t session;
  uint64_t revision;
  uint64_t window_start;
  uint64_t anchor;
  uint64_t focus;
  uint64_t cursor;
  uint64_t viewport_first_block;
  uint32_t viewport_block_count;
  uint32_t text_len;
  uint8_t text[REFRAIN_EVENT_TEXT_BYTES];
} RefrainNativeRequest;
typedef struct RefrainNativeResponse {
  uint32_t status;
  uint16_t protocol_version;
  uint16_t api_version;
  uint32_t capabilities;
  uint16_t action;
  uint16_t reserved;
  uint64_t session;
  uint64_t revision;
  uint64_t total_bytes;
  uint64_t total_blocks;
  uint64_t window_start;
  uint64_t first_block;
  uint32_t block_count;
  uint32_t text_len;
  uint32_t composition_len;
  uint32_t projection_reserved;
  uint64_t selection_anchor;
  uint64_t selection_focus;
  uint64_t composition_start;
  uint64_t composition_end;
  uint64_t composition_cursor;
  uint8_t text[REFRAIN_PROJECTION_BYTES];
  uint8_t composition[REFRAIN_EVENT_TEXT_BYTES];
} RefrainNativeResponse;
RefrainNativeResponse refrain_native_dispatch(RefrainNativeRequest request);
#endif
`;
}

function renderRust(schema: ProtocolSchema, hash: string): string {
  const errors = schema.errors
    .map((error) => `pub const ERROR_${upperSnake(error.name)}: u32 = ${error.code};`)
    .join("\n");
  return `// @generated by scripts/generate-native-protocol.ts; do not edit.

pub const PROTOCOL_VERSION: u16 = ${schema.protocolVersion};
pub const API_VERSION: u16 = ${schema.apiVersion};
pub const CAPABILITY_MASK: u32 = ${schema.capabilityMask};
pub const PROJECTION_BYTES: usize = ${schema.layout.projectionBytes};
pub const EVENT_TEXT_BYTES: usize = ${schema.layout.eventTextBytes};
pub const DEFAULT_VIEWPORT_BLOCKS: u32 = ${schema.layout.defaultViewportBlocks};
#[allow(dead_code)]
pub const PROTOCOL_FINGERPRINT: &str =
    "${hash}";
${errors}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeRequest {
    pub protocol_version: u16,
    pub action: u16,
    pub input: u16,
    pub flags: u16,
    pub session: u64,
    pub revision: u64,
    pub window_start: u64,
    pub anchor: u64,
    pub focus: u64,
    pub cursor: u64,
    pub viewport_first_block: u64,
    pub viewport_block_count: u32,
    pub text_len: u32,
    pub text: [u8; EVENT_TEXT_BYTES],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct RefrainNativeResponse {
    pub status: u32,
    pub protocol_version: u16,
    pub api_version: u16,
    pub capabilities: u32,
    pub action: u16,
    pub reserved: u16,
    pub session: u64,
    pub revision: u64,
    pub total_bytes: u64,
    pub total_blocks: u64,
    pub window_start: u64,
    pub first_block: u64,
    pub block_count: u32,
    pub text_len: u32,
    pub composition_len: u32,
    pub projection_reserved: u32,
    pub selection_anchor: u64,
    pub selection_focus: u64,
    pub composition_start: u64,
    pub composition_end: u64,
    pub composition_cursor: u64,
    pub text: [u8; PROJECTION_BYTES],
    pub composition: [u8; EVENT_TEXT_BYTES],
}

impl RefrainNativeResponse {
    pub const fn empty(status: u32, action: u16) -> Self {
        Self {
            status,
            protocol_version: PROTOCOL_VERSION,
            api_version: API_VERSION,
            capabilities: CAPABILITY_MASK,
            action,
            reserved: 0,
            session: 0,
            revision: 0,
            total_bytes: 0,
            total_blocks: 0,
            window_start: 0,
            first_block: 0,
            block_count: 0,
            text_len: 0,
            composition_len: 0,
            projection_reserved: 0,
            selection_anchor: 0,
            selection_focus: 0,
            composition_start: 0,
            composition_end: 0,
            composition_cursor: 0,
            text: [0; PROJECTION_BYTES],
            composition: [0; EVENT_TEXT_BYTES],
        }
    }
}
`;
}

function renderZig(schema: ProtocolSchema, hash: string): string {
  const errors = schema.errors.map((error) => `${snake(error.name)} = ${error.code}`).join(", ");
  return `// @generated by scripts/generate-native-protocol.ts; do not edit.
const std = @import("std");

pub const host_service = "${schema.service}";
pub const protocol_version: u16 = ${schema.protocolVersion};
pub const api_version: u16 = ${schema.apiVersion};
pub const capability_mask: u32 = ${schema.capabilityMask};
pub const projection_bytes: usize = ${schema.layout.projectionBytes};
pub const event_text_bytes: usize = ${schema.layout.eventTextBytes};
pub const default_viewport_blocks: u32 = ${schema.layout.defaultViewportBlocks};
pub const virtual_block_height: f64 = ${schema.layout.virtualBlockHeight}.0;
pub const protocol_fingerprint = "${hash}";
pub const protocol_magic = [4]u8{ ${magicBytes(schema.magic)} };
pub const response_header_bytes: usize = 52;
pub const response_bytes: usize = response_header_bytes + projection_bytes;

pub const ProtocolError = enum(u32) { ${errors} };

pub const RefrainNativeRequest = extern struct {
    protocol_version: u16,
    action: u16,
    input: u16,
    flags: u16,
    session: u64,
    revision: u64,
    window_start: u64,
    anchor: u64,
    focus: u64,
    cursor: u64,
    viewport_first_block: u64,
    viewport_block_count: u32,
    text_len: u32,
    text: [event_text_bytes]u8,
};

pub const RefrainNativeResponse = extern struct {
    status: u32,
    protocol_version: u16,
    api_version: u16,
    capabilities: u32,
    action: u16,
    reserved: u16,
    session: u64,
    revision: u64,
    total_bytes: u64,
    total_blocks: u64,
    window_start: u64,
    first_block: u64,
    block_count: u32,
    text_len: u32,
    composition_len: u32,
    projection_reserved: u32,
    selection_anchor: u64,
    selection_focus: u64,
    composition_start: u64,
    composition_end: u64,
    composition_cursor: u64,
    text: [projection_bytes]u8,
    composition: [event_text_bytes]u8,
};

pub fn encodeDispatchResponse(response: RefrainNativeResponse) [response_bytes]u8 {
    const requested_text_len: usize = response.text_len;
    const invalid_text = requested_text_len > projection_bytes;
    const overflow = response.session > std.math.maxInt(u32) or
        response.revision > std.math.maxInt(u32) or
        response.total_bytes > std.math.maxInt(u32) or
        response.total_blocks > std.math.maxInt(u32) or
        response.window_start > std.math.maxInt(u32) or
        response.first_block > std.math.maxInt(u32) or
        invalid_text;
    const text_len: usize = if (invalid_text) 0 else requested_text_len;
    var out: [response_bytes]u8 = @splat(0);
    @memcpy(out[0..4], &protocol_magic);
    std.mem.writeInt(u16, out[4..6], response.protocol_version, .little);
    std.mem.writeInt(u16, out[6..8], response.action, .little);
    std.mem.writeInt(u32, out[8..12], if (overflow and response.status == 0) @intFromEnum(ProtocolError.host_failure) else response.status, .little);
    std.mem.writeInt(u16, out[12..14], response.api_version, .little);
    std.mem.writeInt(u16, out[14..16], 0, .little);
    std.mem.writeInt(u32, out[16..20], response.capabilities, .little);
    std.mem.writeInt(u32, out[20..24], wireIndex(response.session), .little);
    std.mem.writeInt(u32, out[24..28], wireIndex(response.revision), .little);
    std.mem.writeInt(u32, out[28..32], wireIndex(response.total_bytes), .little);
    std.mem.writeInt(u32, out[32..36], wireIndex(response.total_blocks), .little);
    std.mem.writeInt(u32, out[36..40], wireIndex(response.window_start), .little);
    std.mem.writeInt(u32, out[40..44], wireIndex(response.first_block), .little);
    std.mem.writeInt(u32, out[44..48], response.block_count, .little);
    std.mem.writeInt(u32, out[48..52], @intCast(text_len), .little);
    @memcpy(out[response_header_bytes..][0..text_len], response.text[0..text_len]);
    return out;
}

pub fn encodedResponseLen(response: RefrainNativeResponse) usize {
    return response_header_bytes + @min(@as(usize, response.text_len), projection_bytes);
}

fn wireIndex(value: u64) u32 {
    return std.math.cast(u32, value) orelse 0;
}

pub fn encodeProtocolError(value: ProtocolError, action: u16) [response_header_bytes]u8 {
    var response = emptyResponse(action);
    response.status = @intFromEnum(value);
    const encoded = encodeDispatchResponse(response);
    return encoded[0..response_header_bytes].*;
}

pub fn emptyResponse(action: u16) RefrainNativeResponse {
    return .{
        .status = 0,
        .protocol_version = protocol_version,
        .api_version = api_version,
        .capabilities = capability_mask,
        .action = action,
        .reserved = 0,
        .session = 0,
        .revision = 0,
        .total_bytes = 0,
        .total_blocks = 0,
        .window_start = 0,
        .first_block = 0,
        .block_count = 0,
        .text_len = 0,
        .composition_len = 0,
        .projection_reserved = 0,
        .selection_anchor = 0,
        .selection_focus = 0,
        .composition_start = 0,
        .composition_end = 0,
        .composition_cursor = 0,
        .text = @splat(0),
        .composition = @splat(0),
    };
}
`;
}

function renderTypeScript(schema: ProtocolSchema, hash: string): string {
  const errors = schema.errors
    .map((error) => `export const ERROR_${upperSnake(error.name)} = ${error.code};`)
    .join("\n");
  const magicChecks = [...schema.magic]
    .map((character, index) => `byte(bytes, ${index}) === ${character.charCodeAt(0)}`)
    .join(" &&\n    ");
  return `// @generated by scripts/generate-native-protocol.ts; do not edit.

export const HOST_SERVICE = "${schema.service}";
export const PROTOCOL_VERSION = ${schema.protocolVersion};
export const API_VERSION = ${schema.apiVersion};
export const CAPABILITY_MASK = ${schema.capabilityMask};
export const PROJECTION_BYTES = ${schema.layout.projectionBytes};
export const EVENT_TEXT_BYTES = ${schema.layout.eventTextBytes};
export const DEFAULT_VIEWPORT_BLOCKS = ${schema.layout.defaultViewportBlocks};
export const VIRTUAL_BLOCK_HEIGHT = ${schema.layout.virtualBlockHeight};
export const PROTOCOL_FINGERPRINT =
  "${hash}";
${errors}

const RESPONSE_HEADER_BYTES = 52;

export function isDispatchResponse(bytes: Uint8Array): boolean {
  if (
    bytes.length < RESPONSE_HEADER_BYTES ||
    !hasMagic(bytes) ||
    readU16(bytes, 4) !== PROTOCOL_VERSION
  )
    return false;
  const textLength = readU32(bytes, 48);
  return textLength <= PROJECTION_BYTES && bytes.length === RESPONSE_HEADER_BYTES + textLength;
}

export function dispatchResponseStatus(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 8) : 0;
}

export function dispatchResponseAction(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU16(bytes, 6) : 0;
}

export function dispatchResponseApiVersion(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU16(bytes, 12) : 0;
}

export function dispatchResponseCapabilities(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 16) : 0;
}

export function dispatchResponseSession(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 20) : 0;
}

export function dispatchResponseRevision(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 24) : 0;
}

export function dispatchResponseTotalBytes(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 28) : 0;
}

export function dispatchResponseTotalBlocks(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 32) : 0;
}

export function dispatchResponseWindowStart(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 36) : 0;
}

export function dispatchResponseFirstBlock(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 40) : 0;
}

export function dispatchResponseBlockCount(bytes: Uint8Array): number {
  return isDispatchResponse(bytes) ? readU32(bytes, 44) : 0;
}

export function dispatchResponseText(bytes: Uint8Array): Uint8Array {
  if (!isDispatchResponse(bytes)) return new Uint8Array(0);
  return bytes.slice(RESPONSE_HEADER_BYTES);
}

function hasMagic(bytes: Uint8Array): boolean {
  return (
    bytes.length >= 4 &&
    ${magicChecks}
  );
}

function byte(bytes: Uint8Array, offset: number): number {
  if (offset >= bytes.length) return 0;
  return bytes[offset] as number;
}

function readU16(bytes: Uint8Array, offset: number): number {
  return byte(bytes, offset) + byte(bytes, offset + 1) * 256;
}

function readU32(bytes: Uint8Array, offset: number): number {
  return (
    byte(bytes, offset) +
    byte(bytes, offset + 1) * 256 +
    byte(bytes, offset + 2) * 65536 +
    byte(bytes, offset + 3) * 16777216
  );
}
`;
}
