#!/usr/bin/env bun
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the RefRain contributors

/**
 * The documented verification order must work on a clean checkout.
 *
 * `tests/corpora/*.md` are generated by `scripts/freeze-corpora.ts` and are
 * gitignored, while `crates/refrain-core/tests/source_layout.rs` reads them
 * with `include_bytes!` — at compile time, not at test time. So a document
 * that tells a newcomer to run cargo first sends them into
 * `couldn't read .../tests/corpora/ideographic-indent.md` and exit 101 before
 * a single test runs. CI never saw it because CI runs `bun run gate` first.
 *
 * What this gate asserts is the property, not the prose: in each document that
 * publishes the verification sequence, the corpus-generating command appears
 * before the first cargo command. Checking for the exact sentence would pass
 * for a document that merely quotes the right words in the wrong order.
 *
 * The compile-time dependency is asserted too. If `source_layout.rs` ever stops
 * using `include_bytes!` on the corpora, the ordering constraint is gone and
 * this gate should be deleted rather than left as a rule nobody can explain.
 *
 * Injection-verified three ways:
 *   1. Swap the cargo block above `bun run gate` in any listed document → red,
 *      naming that document and both line numbers.
 *   2. Delete the gate/corpora line from a document → red, "never generates".
 *   3. Remove `include_bytes!` from source_layout.rs → red, telling the reader
 *      the premise is gone.
 *
 * ARCHITECTURE.md joined the list after publishing the reverse order for as
 * long as it has had a verification block: cargo above `bun run gate`, which is
 * the exact failure this gate exists to prevent. The gate was correct and its
 * list was short, which is the cheaper of the two ways to be wrong and the
 * harder one to notice — a green run reported that every document it knew
 * about was ordered.
 */

import { readFileSync } from "node:fs";

/**
 * Documents that publish the verification sequence to a reader.
 *
 * Every document that shows a cargo command belongs here. A document outside
 * this list is a second authority for the order, and it is the one that drifts.
 */
const DOCUMENTS = ["docs/AGENTS.md", "docs/CONTRIBUTING.md", "docs/ARCHITECTURE.md"] as const;

/** The file whose compile-time read of the corpora creates the constraint. */
const COMPILE_TIME_READER = "crates/refrain-core/tests/source_layout.rs";

/** Either command generates the corpora: the gate runs freeze-corpora first. */
const GENERATES_CORPORA = /^\s*bun\s+(run\s+gate|run\s+corpora|scripts\/freeze-corpora\.ts)\s*$/;

/** A cargo invocation that must compile the test targets. */
const COMPILES_TESTS = /^\s*cargo\s+(clippy|test|fmt)\b/;

const failures: string[] = [];

const reader = readFileSync(COMPILE_TIME_READER, "utf8");
if (!reader.includes("include_bytes!") || !reader.includes("tests/corpora/")) {
  failures.push(
    `${COMPILE_TIME_READER} no longer reads tests/corpora with include_bytes!.\n` +
      "      The ordering constraint this gate exists for is gone. Delete the gate\n" +
      "      and the ordering note in the documents rather than keeping a rule\n" +
      "      whose reason has disappeared.",
  );
}

for (const path of DOCUMENTS) {
  const lines = readFileSync(path, "utf8").split("\n");

  let generatesAt = -1;
  let compilesAt = -1;
  for (const [index, line] of lines.entries()) {
    if (generatesAt === -1 && GENERATES_CORPORA.test(line)) generatesAt = index + 1;
    if (compilesAt === -1 && COMPILES_TESTS.test(line)) compilesAt = index + 1;
  }

  if (compilesAt === -1) continue; // No cargo command here: nothing to order.

  if (generatesAt === -1) {
    failures.push(
      `${path} runs cargo at line ${compilesAt} but never generates the corpora.\n` +
        "      On a clean checkout that command exits 101 before any test runs.",
    );
    continue;
  }

  if (generatesAt > compilesAt) {
    failures.push(
      `${path} runs cargo at line ${compilesAt} before generating the corpora at line ${generatesAt}.\n` +
        "      On a clean checkout the cargo command exits 101 with\n" +
        '      "couldn\'t read .../tests/corpora/*.md". Put `bun run gate` first,\n' +
        "      matching .github/workflows/gate.yml.",
    );
  }
}

if (failures.length > 0) {
  console.error("FAIL  verify:verification-order");
  for (const failure of failures) console.error(`      ${failure}`);
  process.exit(1);
}

console.log(
  `PASS  verify:verification-order  (${DOCUMENTS.length} documents generate the corpora before cargo)`,
);
