// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// Copyright (c) 2026 2youg1 and the RefRain contributors

//! Write `agent_protocol::skill_doc()` to the requested repository path.
//!
//! Run: `cargo run -p refrain-core --example generate_skill_doc -- <path>`

fn main() {
    let target = std::env::args().nth(1).unwrap_or_else(|| {
        eprintln!("usage: generate_skill_doc <path/to/SKILL.md>");
        std::process::exit(2);
    });

    let body = format!(
        "---\n\
         name: refrain\n\
         description: RefRain 写作工作台的 agent 协议。当你收到一份含 \"# Before / # Context / # Request / # Reply format / # Agent reply\" 的请求文件时，加载本 skill。\n\
         ---\n\n\
         <!-- Generated by `cargo run -p refrain-core --example generate_skill_doc`; do not edit. `agent_protocol::skill_doc()` is authoritative. -->\n\n\
         {}\n\
         ---\n\n\
         {}\n",
        refrain_core::agent_protocol::skill_doc(),
        refrain_core::agent_protocol::error_reference(),
    );

    std::fs::write(&target, body).unwrap_or_else(|error| {
        eprintln!("cannot write {target}: {error}");
        std::process::exit(1);
    });
    println!("wrote {target}");
}
