import { chromium } from "playwright";
import { join } from "node:path";
const docs = import.meta.dir;
const b = await chromium.launch();
const p = await b.newPage({ viewportSize: { width: 1120, height: 1200 }, deviceScaleFactor: 2 });
await p.goto("file://" + join(docs, "logo-combine.html"));
await p.waitForTimeout(400);
await p.screenshot({ path: join(docs, "preview-shots", "logo-combine.png"), fullPage: true });
await b.close();
console.log("combine ok");
